### PR TITLE
bump (go-pivnet): import v7 everywhere

### PR DESCRIPTION
**Pull request by crhntr**
dependabot is not bumping major versions so I am doing it manually

### CODE REVIEW

**Comment by crhntr** [comment]
I just rebased the PR on main.

**Comment by crhntr** [comment]
Those were probably part of old code that has since been removed. This PR is really old.

**Comment by crhntr** [comment]
> Those were probably part of old code that has since been removed. This PR is really old. I'll clean it up.

Looks like the generate statements were a bit off. I fixed them and ran generate again. This should be good now. I guess the find and replace for `interface{}` -> `any` was a bit aggressive. I should not have changed the contents of generated files.

**Review by pabloarodas — APPROVED** [review]
Looks good to me now

**Pull request merged**
